name: Test AirportParking

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: '16'
          distribution: 'corretto'
          cache: maven

      - name: Test with Maven
        run: mvn clean test
